def mvnHome   
pipeline {
   agent any
   stages{
      stage('Setting_Up Selenium Grid') {
         steps{        
			
			bat(/docker version/)
			bat(/docker info/)
			bat(/docker compose version/)
			bat(/mvn --version/)
			bat(/docker system prune -a --volumes -f/)
			bat(/docker compose up -d --no-color --wait/)
            bat(/docker compose ps/)
			// Get some code from a GitHub repository
			//git 'https://github.com/Ahmed1891994/JAVAProject_Demo_framework2023.git'
			
         }
      }
      stage('Run Test') {
         steps{
         	script {
	         	// Get the Maven tool.
				// ** NOTE: This 'M3' Maven tool must be configured
				// **       in the global configuration.
				mvnHome = tool 'MAVEN_HOME'
			}
           // Run the maven build
			withEnv(["MVN_HOME=$mvnHome"]) {
                bat(/"%MVN_HOME%\bin\mvn" clean test/)
        	}
         }
      }
      stage('Tearing Down Selenium Grid') {
          steps {
             testNG(reportFilenamePattern: '**/testng-results.xml')
			 bat(/docker compose down/)
          }
        }   
   }
}